### ISSUE TITLE
Release new Version

### ISSUE THREAD

**Issue by tedgarb** [voxpupuli/puppet-rhsm#141]
Hello,

Thank you for merging my PRs at the end of last year. Is there any chance a new release could get cut incorporating the PRs, specifically the second one that was merged after the most recent release?

Thank you,
Edward

**Comment by treydock** [comment]
@tedgarb What PR do you need released?  Does 5.2.0 not have it ?

**Comment by tedgarb** [comment]
#135, which was merged in 51b08d4 just after 5.2.0 / 453d1f9

**Comment by treydock** [comment]
5.3.0 is released that includes #135
