### ISSUE TITLE
RHNSM-register fails

### ISSUE THREAD

**Issue by rsponholtz** [voxpupuli/puppet-rhsm#38]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: enterprise 2016.1.2
- Ruby:
- Distribution:
- Module version:
- RHEL version: Red Hat Enterprise Linux Server release 7.3 

## How to reproduce (e.g Puppet code you use)
basic configuration with username/password only.  trying to register a new machine and the RHNSM-subscribe exec fails.

## What are you seeing
RHNSM-subscribe fails without actually registering the machine

## What behaviour did you expect instead
RHNSM-register to actually register the machine

## Any additional information you'd like to impart
this is the offending code in init.pp:

  exec { 'RHNSM-register':
    command => "subscription-manager register --name='${::fqdn}'${_user}${_password}${_org}${_activationkey}${\
proxycli}",
    onlyif  => 'subscription-manager identity  | grep "not yet registered"',
    path    => '/bin:/usr/bin:/usr/sbin',
    require => Package['subscription-manager'],
    logoutput => true,
  }

the trouble here is that subscription-manager will send the "not yet registered" message to stderr, rather than stdout, so the grep will never find any lines.  The fix is simply:

 onlyif  => 'subscription-manager identity  2>&1 | grep "not yet registered"',

which will pipe the stderr and stdout output from subscription-manager to the grep command, which finds it, and will result in an exit status of 0 (zero), causing the command => to execute.

This is not an issue on the RHNSM-subscribe, because subscription-manager list sends its output to stdout even if the status is unknown.  However, it may be safest to use the 2>&1 anyway, which will work in either case.

**Comment by tux-o-matic** [comment]
I think we can close this issue now.

**Comment by rsponholtz** [comment]
Super, thanks!
