### ISSUE TITLE
repo_optional always caused puppet run to make change

### ISSUE THREAD

**Issue by cohdjn** [voxpupuli/puppet-rhsm#58]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.5
- Ruby: 2.1.9p490
- Distribution: RHEL7
- Module version: 2.1.1

## How to reproduce (e.g Puppet code you use)
```
class { '::rhsm':
  rh_user => 'my username',
  rh_password => 'my password',
  repo_optional => true,
}
```
## What are you seeing
After every puppet run, the following is returned:
```
Notice: /Stage[main]/Rhsm/Rhsm::Repo[rhel-7-server-optional-rpms]/Yumrepo[rhel-7-server-optional-rpms]/enabled: enabled changed ' 1' to 'True'
```
## What behaviour did you expect instead
I expected the module would only apply the change once to enable the repo and then not do anything again unless the repo was changed by an outside influence.

**Comment by bastelfreak** [comment]
Hi @cohdjn, thanks for this issue. Are you able to provide a PR for this, or a rspec test that shows this error?

**Comment by cohdjn** [comment]
I wasn't able to do a PR because I can't nail down exactly why it was happening.  I see you calling the yumrepo resource but the documentation leads me to believe that it's fine?

**Comment by ekohl** [comment]
Could you show what's in the ```rhel-7-server-optional-rpms``` file ```/etc/yum.repos.d```? I suspect that there's something in it that the ```yumrepo``` provider can't parse to a boolean since it changing from ```' 1'``` (note the extra space).

**Comment by cohdjn** [comment]
Here's what that section looks like before a puppet run:

```
[rhel-7-server-optional-rpms]
metadata_expire = 86400
sslclientcert = /etc/pki/entitlement/1490749552781399655.pem
baseurl = https://cdn.redhat.com/content/dist/rhel/server/7/$releasever/$basearch/optional/os
ui_repoid_vars = releasever basearch
sslverify = 1
name = Red Hat Enterprise Linux 7 Server - Optional (RPMs)
sslclientkey = /etc/pki/entitlement/1490749552781399655-key.pem
gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
enabled = 1
sslcacert = /etc/rhsm/ca/redhat-uep.pem
gpgcheck = 1
```

This is what that section looks like after a puppet run:

```
[rhel-7-server-optional-rpms]
metadata_expire= 86400
sslclientcert= /etc/pki/entitlement/1490749552781399655.pem
baseurl= https://cdn.redhat.com/content/dist/rhel/server/7/$releasever/$basearch/optional/os
ui_repoid_vars= releasever basearch
sslverify= 1
name= Red Hat Enterprise Linux 7 Server - Optional (RPMs)
sslclientkey= /etc/pki/entitlement/1490749552781399655-key.pem
gpgkey= file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
enabled=True
sslcacert= /etc/rhsm/ca/redhat-uep.pem
gpgcheck= 1
```

**Comment by ekohl** [comment]
That actually surprises me. It looks like the space handling is very weird. I suppose we can change the enabled to ```1``` and see if that works at https://github.com/voxpupuli/puppet-rhsm/blob/625311494e1405b9d0bed87b93e0ae7dee48e9ad/manifests/repo.pp#L16

IMHO this is a bug in the puppet yumrepo provider rather than our module.

**Comment by cohdjn** [comment]
Have a look at #59.  Changing enabled from true to '1' appears to have fixed the problem (for me at least).

**Comment by alexjfisher** [comment]
@ekohl This [code ](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/type/yumrepo.rb#L30-L32) looks very insufficient.

**Comment by ekohl** [comment]
@cohdjn good to hear that.

@alexjfisher you're right, that's very naive.

**Comment by alexjfisher** [comment]
Also see https://github.com/puppetlabs/puppet/pull/4450 and https://github.com/voxpupuli/puppet-rhsm/pull/17

**Comment by ekohl** [comment]
I assume this can be closed now.

**Comment by cohdjn** [comment]
Yes this can be closed.  Thank you for your help!
