### ISSUE TITLE
help with process in using this module

### ISSUE THREAD

**Issue by brettswift** [voxpupuli/puppet-rhsm#6]
Hopefully you don't mind the question here. 

We're new to RH Satellite 6 and wondering how you manage initially subscribing a server. 

The registration command doesn't pass in a serverurl,  which ends up sending this to the RH Customer Portal.   I'm assuming in your server clone process there is a script or something that configures this server to run against your on-premise Satellite server.  Is that true? 

ex: 
https://github.com/gerapeldoorn/puppet-rhsm/blob/98ae0ee3a5eaeccc9e3afafbca2eec6971735512/manifests/init.pp#L61

**Comment by gerapeldoorn** [comment]
Hi,

Sorry for the late reply.

It should be configured to check in with your Satellite server with the
configfile: /etc/rhsm/rhsm.conf

It is managed, but the content is not (although there is a template).

Problem is, i created this module for a client years ago and I dont have
any way to test updates. I'm in the process of moving it over to Puppet
Community for maintenance.

Ger

*Ger Apeldoorn*
Freelance Puppet consultant/trainer

Swalmstraat 1
8303 JD Emmeloord
The Netherlands
*Mobile:* +31 6 46424945
*Email:* info@gerapeldoorn.nl
*Website: http://puppetspecialist.nl <http://puppetspecialist.nl>*
*Website: http://autiplan.nl <http://autiplan.nl>*
*Website: http://mijneigenplan.nl <http://mijneigenplan.nl>*

[image: LinkedIn] <http://www.linkedin.com/in/gerapeldoorn>[image: Twitter]
<https://twitter.com/gerapeldoorn>[image: Google+]
<https://plus.google.com/112857204167622817442/posts>


2016-07-14 19:59 GMT+02:00 Brett <notifications@github.com>:

**Comment by kallies** [comment]
As said by @gerapeldoorn the [rhsm.conf is managed as file resource](https://github.com/voxpupuli/puppet-rhsm/blob/00d3af01c944155fc1615afb1d9af43523d11030/manifests/init.pp#L108). BTW, I just realized there is no dependency defined from exec['RHSM-register'].
Alternatively `subscription-manager register` can take a `--serverurl=` option.

**Comment by kallies** [comment]
@brettswift  #57 should fix your issue. I'm using the rhsm module for registering the Satellite 6 server against subscription.rhsm.redhat.com and as well for registering the hosts against Satellite 6.

**Comment by vinzent** [comment]
closed by #57
