### ISSUE TITLE
Puppet agent run fails if the system is not already registered with RHSM

### ISSUE THREAD

**Issue by SohamChakraborty** [voxpupuli/puppet-rhsm#62]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.4
- Ruby: ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
- Distribution: RHEL6.9
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)
```
class profiles::rhsm {
  class { 'rhsm':
    rh_user     => 'my_username',
    rh_password => 'ENC[encrypted_password]',
    pool        => 'pool-id'
  }
}
```

## What are you seeing

```
# subscription-manager list --consumed
No consumed subscription pools to list

# puppet agent -t 
Notice: Local environment: 'development' doesn't match server specified node environment 'testenv', switching agent to 'testenv'.
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for hostname.org.com
Info: Applying configuration version '1514401504'
Notice: /Stage[main]/Rhsm/Exec[RHSM-subscribe]/returns: This system is not yet registered. Try 'subscription-manager register --help' for more information.
Error: 'subscription-manager attach --pool=pool-id' returned 1 instead of one of [0]
Error: /Stage[main]/Rhsm/Exec[RHSM-subscribe]/returns: change from notrun to 0 failed: 'subscription-manager attach --pool=pool-id' returned 1 instead of one of [0]
Notice: Applied catalog in 2.24 seconds
```

## What behaviour did you expect instead
It should subscribe the system without any problem.

## Output log
Given

## Any additional information you'd like to impart
The additional point is that this host was subscribed to a different pool. So, before doing the puppet run, I did the following:

```
# subscription-manager remove --all
# subscription-manager unregister
# subscription-manager clean
```

Then, I executed the agent run and it failed. However, when I tried to register the host manually, it threw me an error saying:
'This system has already been registered with Red Hat using RHN Classic.
Your system is being registered again using Red Hat Subscription Management. Red Hat recommends that customers only register once.'

I am kind of convinced that this error is not related with the agent run failure. But again, I am also convinced that I can't be the first person to find a problem of this nature.

**Comment by kallies** [comment]
`This system has already been registered with Red Hat using RHN Classic.`

Can you verify that there is _no_ `/etc/sysconfig/rhn/systemid`?

**Comment by SohamChakraborty** [comment]
You are correct. Moving the systemid file fixed the issue. 

Thanks,
