### ISSUE TITLE
Features request: SCL repos

### ISSUE THREAD

**Issue by ubellavance** [voxpupuli/puppet-rhsm#66]
Feature request: the ability of adding SCL repositories

Syntax: 

`subscription-manager repos --enable rhel-server-rhscl-${::operatingsystemmajrelease}-rpms`

It would be even better if we could enable arbitrary repositories, like `rhel-7-server-restricted-maintenance-oracle-java-rpms` for example.

**Comment by kallies** [comment]
`rhsm::repo` is a defined type, so this _should_ not be a lot of work (but in the end it might be ;-))

**Comment by kallies** [comment]
Solved by #78

**Comment by kallies** [comment]
@ubellavance is this issue solved for you?

**Comment by ubellavance** [comment]
I think so. I unfortunately don't have time to test.  But it's cool to see that there can be conditional facts, I didn't know.  Closing.
