### ISSUE TITLE
Yumrepo target parameter does not work

### ISSUE THREAD

**Issue by vinzent** [voxpupuli/puppet-rhsm#68]
https://github.com/voxpupuli/puppet-rhsm/blob/master/manifests/repo.pp#L18 uses the yumrepo target parameter.

According [PUP-2782 Yumrepo target attribute does not work](https://tickets.puppetlabs.com/browse/PUP-2782) the parameter doesn't work up to  Puppet 5.5.x ([and is not yet fixed](https://tickets.puppetlabs.com/browse/PUP-2782?focusedCommentId=539887&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-539887))

**Comment by tux-o-matic** [comment]
Anyway, we've had problems with this because of [another Type bug](https://tickets.puppetlabs.com/browse/PUP-6639) which has just been fixed in 5.5.0.

Basically supporting Red Hat's own repositories should have been the most obvious thing to do with the Yumrepo Type yet it's been totally broken.

**Comment by kallies** [comment]
Solved with #78

**Comment by kallies** [comment]
@vinzent maybe you want to close this issue as it is not relevant anymore.

**Comment by ghoneycutt** [comment]
Closing this issue as link above is merged. Please re-open if needed.
