### ISSUE TITLE
Update rhsm.conf template

### ISSUE THREAD

**Issue by kallies** [voxpupuli/puppet-rhsm#85]
Current subscription-manager packages (e.g. 1.21.10-3.el7_6) deliver an updated `rhsm.conf`. Therefore the template should be updated. New values are:

```
repomd_gpg_url =
auto_enable_yum_plugins = 1
inotify = 1
```

See also https://github.com/candlepin/subscription-manager/blob/master/etc-conf/rhsm.conf#L86

## Affected Puppet, Ruby, OS and module versions/distributions

- Distribution: RHEL 7
- Module version: 3.2.0

## How to reproduce (e.g Puppet code you use)

```
class { 'rhsm':
  activationkey         => 'act-lce-rhel-7',
  org                   => 'satellite_organization',
  servername            => 'satellite.example.com',
  serverprefix          => '/rhsm',
  repo_ca_cert_filename => 'katello-server-ca.pem',
  repo_ca_cert_source   => 'puppet:///modules/profile/katello-server-ca.crt',
  full_refresh_on_yum   => 1,
  baseurl               => 'https://satellite.example.com/pulp/repos',
}
```

## What are you seeing

Removal of default parameters

## What behaviour did you expect instead

Keeping defaults.

## Output log

```
- repomd_gpg_url =
- auto_enable_yum_plugins = 1
- inotify = 1
```

**Comment by bastelfreak** [comment]
Hi @kallies, thanks for reporting this. Are you able to provide a PR for it?
