### ISSUE TITLE
Use types and providers for subscriptions and repositories

### ISSUE THREAD

**Issue by kallies** [voxpupuli/puppet-rhsm#87]
@crayfishx provides a puppet-rhsm module with a slightly different focus. We are currently using a mix of both modules, because we need to enable additional subscriptions (products on Satellite 6) through Puppet (not only by the use of an activation key or multiple activation keys).

My proposal is to combine both modules (both are Apache License 2.0). An option would be to import the types and providers (`rh_subscription`/`rh_repo`) from crayfishx/rhsm. Adding those would also allow us to get rid of some `exec` resources and maybe resource dependencies.

**Comment by ekohl** [comment]
:+1: In general I'm in favor of an ecosystem converging on a single module where possible. I'd in favor of this approach.
